[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/amlich"
  to = "/.netlify/functions/api/amlich"
  status = 200

[[redirects]]
  from = "/ping"
  to = "/.netlify/functions/api/ping"
  status = 200

[[redirects]]
  from = "/home"
  to = "/.netlify/functions/api/home"
  status = 200
